SCHEMA_FIELD_KEY = "field"
SCHEMA_TYPE_KEY = "type"
SCHEMA_EXAMPLE_DATA_KEY = "example_data"
SCHEMA_DESCRIPTION_KEY = "description"
SCHEMA_SELECTED_KEY= "selected"
SCHEMA_NEW_FIELD_NAME = "new_field_name"



# TEXT 
TEXT_FORMAT = "TEXT"
TEXT_PLAIN_CONTENT_TYPE="text/plain"
TEXT_HTML_CONTENT_TYPE="text/html"
TEXT_CONTENT_TYPE_LIST=[TEXT_PLAIN_CONTENT_TYPE,TEXT_HTML_CONTENT_TYPE]


# XML
XML_FORMAT = "XML"
XML_CONTENT_TYPE_LIST = ["text/xml","application/xml","application/rdf+xml","application/owl+xml","application/rdf+xml","application/atom+xml","application/rss+xml"]

# JSON 
JSON_FORMAT = "JSON"
JSON_CONTENT_TYPE="application/json"
JSON_CONTENT_TYPE_LIST = [JSON_CONTENT_TYPE]

# CSV
CSV_FORMAT = "CSV"
CSV_CONTENT_TYPE="text/csv"
CSV1_CONTENT_TYPE="application/csv"
TSV_CONTENT_TYPE = "text/tab-separated-values"
CSV_CONTENT_TYPE_LIST = [CSV_CONTENT_TYPE, CSV1_CONTENT_TYPE,TSV_CONTENT_TYPE]


# EXCEL
XLSX_FORMAT= "XLSX"
# XLSB_FORMAT="XLSB"
XLS_FORMAT="XLS"
# XLSM_FORMAT="XLSM"


XLSX_CONTENT_TYPE = ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]
# XLSB_CONTENT_TYPE = ["application/vnd.ms-excel.sheet.binary.macroEnabled.12"]
XLS_CONTENT_TYPE=["application/vnd.ms-excel"]
# XLSM_CONTENT_TYPE=["application/vnd.ms-excel.sheet.macroEnabled.12"]

# EXCEL_CONTENT_TYPE_LIST= XLSX_CONTENT_TYPE + XLSB_CONTENT_TYPE + XLS_CONTENT_TYPE + XLSM_CONTENT_TYPE
EXCEL_CONTENT_TYPE_LIST= XLSX_CONTENT_TYPE  + XLS_CONTENT_TYPE 
# EXCEL_FORMAT_LIST = [ XLSX_FORMAT,XLSB_FORMAT,XLS_FORMAT,XLSM_FORMAT]
EXCEL_FORMAT_LIST = [ XLSX_FORMAT,XLS_FORMAT]

# Image
APNG_FORMAT="APNG"
AVIF_FORMAT="AVIF"
GIF_FORMAT="GIF"
JPEG_FORMAT="JPEG"
PNG_FORMAT="PNG"
SVG_FORMAT="SVG"
WEBP_FORMAT="WEBP"

APNG_CONTENT_TYPE=["image/apng"]
AVIF_CONTENT_TYPE=["image/avif"]
GIF_CONTENT_TYPE=["image/gif"]
JPEG_CONTENT_TYPE=["image/jpeg"]
PNG_CONTENT_TYPE=["image/png"]
SVG_CONTENT_TYPE=["image/svg+xml"]
WEBP_CONTENT_TYPE=["image/webp"]

IMAGE_FORMAT_LIST=[APNG_FORMAT,AVIF_FORMAT,GIF_FORMAT,JPEG_FORMAT,PNG_FORMAT,SVG_FORMAT,WEBP_FORMAT]
IMAGE_CONTENT_TYPE_LIST = APNG_CONTENT_TYPE + AVIF_CONTENT_TYPE + GIF_CONTENT_TYPE +JPEG_CONTENT_TYPE + PNG_CONTENT_TYPE +SVG_CONTENT_TYPE + WEBP_CONTENT_TYPE



SCHEMA_LESS_FORMAT_LIST = IMAGE_FORMAT_LIST + [TEXT_FORMAT] + [XML_FORMAT]
SCHEMA_LESS_CONTENT_TYPE_LIST = IMAGE_CONTENT_TYPE_LIST + TEXT_CONTENT_TYPE_LIST + XML_CONTENT_TYPE_LIST


ALL_FORMAT_LIST =  [JSON_FORMAT] + [TEXT_FORMAT] + [CSV_FORMAT] + EXCEL_FORMAT_LIST \
                    + IMAGE_FORMAT_LIST + [XML_FORMAT]

ALL_CONTENT_TYPE_LIST =  JSON_CONTENT_TYPE_LIST + TEXT_CONTENT_TYPE_LIST + CSV_CONTENT_TYPE_LIST + EXCEL_CONTENT_TYPE_LIST + IMAGE_CONTENT_TYPE_LIST + XML_CONTENT_TYPE_LIST